# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('imagem_principal', models.URLField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, default='Caio Marinho', max_length=300, null=True)),
                ('views', models.CharField(blank=True, default='385', max_length=300, null=True)),
                ('comments', models.CharField(blank=True, default='12', max_length=300, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
