# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190215_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_download',
            field=models.URLField(blank=True, null=True),
        ),
    ]
